/*
eHelply SDK - 1.1.119

eHelply SDK for SuperStack Services

API version: 1.1.119
Contact: support@ehelply.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ehelply

import (
	"encoding/json"
)

// DeleteFile200Response struct for DeleteFile200Response
type DeleteFile200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewDeleteFile200Response instantiates a new DeleteFile200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteFile200Response() *DeleteFile200Response {
	this := DeleteFile200Response{}
	return &this
}

// NewDeleteFile200ResponseWithDefaults instantiates a new DeleteFile200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteFile200ResponseWithDefaults() *DeleteFile200Response {
	this := DeleteFile200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeleteFile200Response) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteFile200Response) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeleteFile200Response) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeleteFile200Response) SetMessage(v string) {
	o.Message = &v
}

func (o DeleteFile200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteFile200Response struct {
	value *DeleteFile200Response
	isSet bool
}

func (v NullableDeleteFile200Response) Get() *DeleteFile200Response {
	return v.value
}

func (v *NullableDeleteFile200Response) Set(val *DeleteFile200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteFile200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteFile200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteFile200Response(val *DeleteFile200Response) *NullableDeleteFile200Response {
	return &NullableDeleteFile200Response{value: val, isSet: true}
}

func (v NullableDeleteFile200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteFile200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


