/*
eHelply SDK - 1.1.96

eHelply SDK for SuperStack Services

API version: 1.1.96
Contact: support@ehelply.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ehelply

import (
	"encoding/json"
)

// NoteDynamoResponse struct for NoteDynamoResponse
type NoteDynamoResponse struct {
	Uuid string `json:"uuid"`
	Content string `json:"content"`
	Time string `json:"time"`
	Meta NoteMeta `json:"meta"`
}

// NewNoteDynamoResponse instantiates a new NoteDynamoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoteDynamoResponse(uuid string, content string, time string, meta NoteMeta) *NoteDynamoResponse {
	this := NoteDynamoResponse{}
	this.Uuid = uuid
	this.Content = content
	this.Time = time
	this.Meta = meta
	return &this
}

// NewNoteDynamoResponseWithDefaults instantiates a new NoteDynamoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoteDynamoResponseWithDefaults() *NoteDynamoResponse {
	this := NoteDynamoResponse{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *NoteDynamoResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *NoteDynamoResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *NoteDynamoResponse) SetUuid(v string) {
	o.Uuid = v
}

// GetContent returns the Content field value
func (o *NoteDynamoResponse) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *NoteDynamoResponse) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *NoteDynamoResponse) SetContent(v string) {
	o.Content = v
}

// GetTime returns the Time field value
func (o *NoteDynamoResponse) GetTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *NoteDynamoResponse) GetTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *NoteDynamoResponse) SetTime(v string) {
	o.Time = v
}

// GetMeta returns the Meta field value
func (o *NoteDynamoResponse) GetMeta() NoteMeta {
	if o == nil {
		var ret NoteMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *NoteDynamoResponse) GetMetaOk() (*NoteMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *NoteDynamoResponse) SetMeta(v NoteMeta) {
	o.Meta = v
}

func (o NoteDynamoResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["uuid"] = o.Uuid
	}
	if true {
		toSerialize["content"] = o.Content
	}
	if true {
		toSerialize["time"] = o.Time
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableNoteDynamoResponse struct {
	value *NoteDynamoResponse
	isSet bool
}

func (v NullableNoteDynamoResponse) Get() *NoteDynamoResponse {
	return v.value
}

func (v *NullableNoteDynamoResponse) Set(val *NoteDynamoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNoteDynamoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNoteDynamoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoteDynamoResponse(val *NoteDynamoResponse) *NullableNoteDynamoResponse {
	return &NullableNoteDynamoResponse{value: val, isSet: true}
}

func (v NullableNoteDynamoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoteDynamoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


