/*
eHelply SDK - 1.1.114

eHelply SDK for SuperStack Services

API version: 1.1.114
Contact: support@ehelply.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ehelply

import (
	"encoding/json"
)

// CreateMeta200Response struct for CreateMeta200Response
type CreateMeta200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewCreateMeta200Response instantiates a new CreateMeta200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMeta200Response() *CreateMeta200Response {
	this := CreateMeta200Response{}
	return &this
}

// NewCreateMeta200ResponseWithDefaults instantiates a new CreateMeta200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMeta200ResponseWithDefaults() *CreateMeta200Response {
	this := CreateMeta200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateMeta200Response) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMeta200Response) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateMeta200Response) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateMeta200Response) SetMessage(v string) {
	o.Message = &v
}

func (o CreateMeta200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableCreateMeta200Response struct {
	value *CreateMeta200Response
	isSet bool
}

func (v NullableCreateMeta200Response) Get() *CreateMeta200Response {
	return v.value
}

func (v *NullableCreateMeta200Response) Set(val *CreateMeta200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMeta200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMeta200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMeta200Response(val *CreateMeta200Response) *NullableCreateMeta200Response {
	return &NullableCreateMeta200Response{value: val, isSet: true}
}

func (v NullableCreateMeta200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMeta200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


