/*
eHelply SDK - 1.1.87

eHelply SDK for SuperStack Services

API version: 1.1.87
Contact: support@ehelply.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ehelply

import (
	"encoding/json"
)

// NotesValidationError struct for NotesValidationError
type NotesValidationError struct {
	Loc []string `json:"loc"`
	Msg string `json:"msg"`
	Type string `json:"type"`
}

// NewNotesValidationError instantiates a new NotesValidationError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotesValidationError(loc []string, msg string, type_ string) *NotesValidationError {
	this := NotesValidationError{}
	this.Loc = loc
	this.Msg = msg
	this.Type = type_
	return &this
}

// NewNotesValidationErrorWithDefaults instantiates a new NotesValidationError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotesValidationErrorWithDefaults() *NotesValidationError {
	this := NotesValidationError{}
	return &this
}

// GetLoc returns the Loc field value
func (o *NotesValidationError) GetLoc() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Loc
}

// GetLocOk returns a tuple with the Loc field value
// and a boolean to check if the value has been set.
func (o *NotesValidationError) GetLocOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Loc, true
}

// SetLoc sets field value
func (o *NotesValidationError) SetLoc(v []string) {
	o.Loc = v
}

// GetMsg returns the Msg field value
func (o *NotesValidationError) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *NotesValidationError) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *NotesValidationError) SetMsg(v string) {
	o.Msg = v
}

// GetType returns the Type field value
func (o *NotesValidationError) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NotesValidationError) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NotesValidationError) SetType(v string) {
	o.Type = v
}

func (o NotesValidationError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["loc"] = o.Loc
	}
	if true {
		toSerialize["msg"] = o.Msg
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableNotesValidationError struct {
	value *NotesValidationError
	isSet bool
}

func (v NullableNotesValidationError) Get() *NotesValidationError {
	return v.value
}

func (v *NullableNotesValidationError) Set(val *NotesValidationError) {
	v.value = val
	v.isSet = true
}

func (v NullableNotesValidationError) IsSet() bool {
	return v.isSet
}

func (v *NullableNotesValidationError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotesValidationError(val *NotesValidationError) *NullableNotesValidationError {
	return &NullableNotesValidationError{value: val, isSet: true}
}

func (v NullableNotesValidationError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotesValidationError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


