/*
eHelply SDK - 1.1.100

eHelply SDK for SuperStack Services

API version: 1.1.100
Contact: support@ehelply.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ehelply

import (
	"encoding/json"
)

// MetaGet Meta
type MetaGet struct {
	Uuid string `json:"uuid"`
	Basic BasicMeta `json:"basic"`
	Detailed DetailedMetaGet `json:"detailed"`
	Custom *MetaCustom `json:"custom,omitempty"`
	Dates *DatesMeta `json:"dates,omitempty"`
	Fields []Field `json:"fields,omitempty"`
	Children []MetaChildren `json:"children,omitempty"`
	ParentUuid *string `json:"parent_uuid,omitempty"`
}

// NewMetaGet instantiates a new MetaGet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaGet(uuid string, basic BasicMeta, detailed DetailedMetaGet) *MetaGet {
	this := MetaGet{}
	this.Uuid = uuid
	this.Basic = basic
	this.Detailed = detailed
	return &this
}

// NewMetaGetWithDefaults instantiates a new MetaGet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaGetWithDefaults() *MetaGet {
	this := MetaGet{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *MetaGet) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *MetaGet) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *MetaGet) SetUuid(v string) {
	o.Uuid = v
}

// GetBasic returns the Basic field value
func (o *MetaGet) GetBasic() BasicMeta {
	if o == nil {
		var ret BasicMeta
		return ret
	}

	return o.Basic
}

// GetBasicOk returns a tuple with the Basic field value
// and a boolean to check if the value has been set.
func (o *MetaGet) GetBasicOk() (*BasicMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Basic, true
}

// SetBasic sets field value
func (o *MetaGet) SetBasic(v BasicMeta) {
	o.Basic = v
}

// GetDetailed returns the Detailed field value
func (o *MetaGet) GetDetailed() DetailedMetaGet {
	if o == nil {
		var ret DetailedMetaGet
		return ret
	}

	return o.Detailed
}

// GetDetailedOk returns a tuple with the Detailed field value
// and a boolean to check if the value has been set.
func (o *MetaGet) GetDetailedOk() (*DetailedMetaGet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detailed, true
}

// SetDetailed sets field value
func (o *MetaGet) SetDetailed(v DetailedMetaGet) {
	o.Detailed = v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *MetaGet) GetCustom() MetaCustom {
	if o == nil || o.Custom == nil {
		var ret MetaCustom
		return ret
	}
	return *o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaGet) GetCustomOk() (*MetaCustom, bool) {
	if o == nil || o.Custom == nil {
		return nil, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *MetaGet) HasCustom() bool {
	if o != nil && o.Custom != nil {
		return true
	}

	return false
}

// SetCustom gets a reference to the given MetaCustom and assigns it to the Custom field.
func (o *MetaGet) SetCustom(v MetaCustom) {
	o.Custom = &v
}

// GetDates returns the Dates field value if set, zero value otherwise.
func (o *MetaGet) GetDates() DatesMeta {
	if o == nil || o.Dates == nil {
		var ret DatesMeta
		return ret
	}
	return *o.Dates
}

// GetDatesOk returns a tuple with the Dates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaGet) GetDatesOk() (*DatesMeta, bool) {
	if o == nil || o.Dates == nil {
		return nil, false
	}
	return o.Dates, true
}

// HasDates returns a boolean if a field has been set.
func (o *MetaGet) HasDates() bool {
	if o != nil && o.Dates != nil {
		return true
	}

	return false
}

// SetDates gets a reference to the given DatesMeta and assigns it to the Dates field.
func (o *MetaGet) SetDates(v DatesMeta) {
	o.Dates = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *MetaGet) GetFields() []Field {
	if o == nil || o.Fields == nil {
		var ret []Field
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaGet) GetFieldsOk() ([]Field, bool) {
	if o == nil || o.Fields == nil {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *MetaGet) HasFields() bool {
	if o != nil && o.Fields != nil {
		return true
	}

	return false
}

// SetFields gets a reference to the given []Field and assigns it to the Fields field.
func (o *MetaGet) SetFields(v []Field) {
	o.Fields = v
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *MetaGet) GetChildren() []MetaChildren {
	if o == nil || o.Children == nil {
		var ret []MetaChildren
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaGet) GetChildrenOk() ([]MetaChildren, bool) {
	if o == nil || o.Children == nil {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *MetaGet) HasChildren() bool {
	if o != nil && o.Children != nil {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []MetaChildren and assigns it to the Children field.
func (o *MetaGet) SetChildren(v []MetaChildren) {
	o.Children = v
}

// GetParentUuid returns the ParentUuid field value if set, zero value otherwise.
func (o *MetaGet) GetParentUuid() string {
	if o == nil || o.ParentUuid == nil {
		var ret string
		return ret
	}
	return *o.ParentUuid
}

// GetParentUuidOk returns a tuple with the ParentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaGet) GetParentUuidOk() (*string, bool) {
	if o == nil || o.ParentUuid == nil {
		return nil, false
	}
	return o.ParentUuid, true
}

// HasParentUuid returns a boolean if a field has been set.
func (o *MetaGet) HasParentUuid() bool {
	if o != nil && o.ParentUuid != nil {
		return true
	}

	return false
}

// SetParentUuid gets a reference to the given string and assigns it to the ParentUuid field.
func (o *MetaGet) SetParentUuid(v string) {
	o.ParentUuid = &v
}

func (o MetaGet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["uuid"] = o.Uuid
	}
	if true {
		toSerialize["basic"] = o.Basic
	}
	if true {
		toSerialize["detailed"] = o.Detailed
	}
	if o.Custom != nil {
		toSerialize["custom"] = o.Custom
	}
	if o.Dates != nil {
		toSerialize["dates"] = o.Dates
	}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	if o.Children != nil {
		toSerialize["children"] = o.Children
	}
	if o.ParentUuid != nil {
		toSerialize["parent_uuid"] = o.ParentUuid
	}
	return json.Marshal(toSerialize)
}

type NullableMetaGet struct {
	value *MetaGet
	isSet bool
}

func (v NullableMetaGet) Get() *MetaGet {
	return v.value
}

func (v *NullableMetaGet) Set(val *MetaGet) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaGet) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaGet(val *MetaGet) *NullableMetaGet {
	return &NullableMetaGet{value: val, isSet: true}
}

func (v NullableMetaGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


